CREATE TABLE `customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customerGuid` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `firstName` VARCHAR(80) NOT NULL,
  `lastName` VARCHAR(80) NOT NULL,
  `dateOfBirth` DATE DEFAULT NULL,
  `gender` ENUM('male','female') NOT NULL,
  `address` VARCHAR(150) DEFAULT NULL,
  `city` VARCHAR(50) NOT NULL,
  `state` VARCHAR(80) DEFAULT NULL,
  `stateCode` VARCHAR(2) DEFAULT NULL,
  `email` VARCHAR(100) DEFAULT NULL,
  `phoneNumber` VARCHAR(20) NOT NULL,
  `gstin` VARCHAR(15) DEFAULT NULL,
  `pan` VARCHAR(10) DEFAULT NULL,
  `remarks` TEXT,
  `creditBalance` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  `imagePath` VARCHAR(255) DEFAULT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_customers_customerGuid` (`customerGuid`),
  UNIQUE KEY `customers_email` (`email`),
  KEY `idx_customers_deletedAt_createdAt` (`deletedAt`, `createdAt`),
  KEY `idx_customers_phoneNumber` (`phoneNumber`),
  KEY `idx_customers_gstin` (`gstin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
