CREATE TABLE `invoicelineitems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `invoiceId` INT NOT NULL,
  `productId` INT DEFAULT NULL,
  `lineType` ENUM('product', 'oldGold', 'stone', 'labour') NOT NULL DEFAULT 'product',
  `description` VARCHAR(255) DEFAULT NULL,
  `hsnCode` VARCHAR(8) DEFAULT NULL,
  `purityCode` VARCHAR(10) DEFAULT NULL,
  `grossWeight` DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  `netWeight` DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  `stoneWeight` DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  `ratePerGram` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  `metalValue` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `makingCharge` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `stoneCharge` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `wastageCharge` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `discountAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `taxableAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `cgst` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `sgst` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `igst` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `lineTotal` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_invoicelineitems_invoiceId` (`invoiceId`),
  KEY `idx_invoicelineitems_productId` (`productId`),
  KEY `idx_invoicelineitems_lineType` (`lineType`),
  CONSTRAINT `fk_invoicelineitems_invoice` FOREIGN KEY (`invoiceId`) REFERENCES `invoices` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_invoicelineitems_product` FOREIGN KEY (`productId`) REFERENCES `products` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_invoicelineitems_purity`  FOREIGN KEY (`purityCode`) REFERENCES `purities` (`code`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
