CREATE TABLE `invoices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `invoiceGuid` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `invoiceNumber` VARCHAR(40) NOT NULL,
  `hsn` VARCHAR(8) NOT NULL DEFAULT '7113',
  `placeOfSupply` VARCHAR(80) DEFAULT NULL,
  `rateSnapshot` JSON DEFAULT NULL,
  `subTotalTaxable` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `totalCgst` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `totalSgst` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `totalIgst` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `totalDiscount` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `totalMakingCharge` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `totalStoneCharge` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `totalWastageCharge` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `oldGoldCreditAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `savingSchemeRedemption` JSON DEFAULT NULL,
  `roundOffAmount` DECIMAL(6, 2) NOT NULL DEFAULT 0.00,
  `grandTotal` DECIMAL(14, 2) NOT NULL,
  `isPaymentDone` TINYINT(1) NOT NULL DEFAULT 0,
  `isEinvoice` TINYINT(1) NOT NULL DEFAULT 0,
  `irn` VARCHAR(64) DEFAULT NULL,
  `qrCodeData` TEXT,
  `remarks` TEXT,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cancelledAt` DATETIME DEFAULT NULL,
  `cancelReason` VARCHAR(255) DEFAULT NULL,
  `soldToCustomer` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_invoices_invoiceGuid` (`invoiceGuid`),
  UNIQUE KEY `uk_invoices_invoiceNumber` (`invoiceNumber`),
  KEY `idx_invoices_soldToCustomer` (`soldToCustomer`),
  KEY `idx_invoices_cancelledAt_createdAt` (`cancelledAt`, `createdAt`),
  CONSTRAINT `fk_invoices_soldToCustomer` FOREIGN KEY (`soldToCustomer`) REFERENCES `customers` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
