CREATE TABLE `karigarjobcards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jobGuid` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `karigarId` INT NOT NULL,
  `issueDate` DATE NOT NULL,
  `expectedReturnDate` DATE DEFAULT NULL,
  `receivedDate` DATE DEFAULT NULL,
  `issuedGrossWeight` DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  `issuedPurityCode` VARCHAR(10) DEFAULT NULL,
  `issuedStones` JSON DEFAULT NULL,
  `receivedGrossWeight` DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  `receivedNetWeight` DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  `receivedStoneWeight` DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  `wastagePercentAllowed` DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
  `wastageGramsActual` DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  `makingCharge` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `settlementAmount` DECIMAL(14, 2) NOT NULL DEFAULT 0.00,
  `settlementPaymentMode` VARCHAR(20) DEFAULT NULL,
  `settlementRefNumber` VARCHAR(80) DEFAULT NULL,
  `settledAt` DATETIME DEFAULT NULL,
  `productId` INT DEFAULT NULL,
  `description` TEXT,
  `remarks` TEXT,
  `status` ENUM('issued', 'received', 'settled', 'cancelled') NOT NULL DEFAULT 'issued',
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_karigarjobcards_jobGuid` (`jobGuid`),
  KEY `idx_karigarjobcards_karigarId` (`karigarId`),
  KEY `idx_karigarjobcards_status` (`status`),
  KEY `idx_karigarjobcards_issueDate` (`issueDate`),
  CONSTRAINT `fk_karigarjobcards_karigar` FOREIGN KEY (`karigarId`) REFERENCES `karigars` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_karigarjobcards_purity`  FOREIGN KEY (`issuedPurityCode`) REFERENCES `purities` (`code`) ON UPDATE CASCADE,
  CONSTRAINT `fk_karigarjobcards_product` FOREIGN KEY (`productId`) REFERENCES `products` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
