CREATE TABLE `karigarledger` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ledgerGuid` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `karigarId` INT NOT NULL,
  `jobId` INT DEFAULT NULL,
  `entryType` ENUM('issue', 'receive', 'payment', 'adjustment') NOT NULL,
  `direction` ENUM('debit', 'credit') NOT NULL,
  `weightGrams` DECIMAL(10, 3) DEFAULT NULL,
  `amount` DECIMAL(14, 2) DEFAULT NULL,
  `txnDate` DATE NOT NULL DEFAULT (CURRENT_DATE),
  `notes` VARCHAR(255) DEFAULT NULL,
  `actorUserId` INT DEFAULT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_karigarledger_ledgerGuid` (`ledgerGuid`),
  KEY `idx_karigarledger_karigarId_txnDate` (`karigarId`, `txnDate`),
  KEY `idx_karigarledger_jobId` (`jobId`),
  CONSTRAINT `fk_karigarledger_karigar` FOREIGN KEY (`karigarId`) REFERENCES `karigars` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_karigarledger_job`     FOREIGN KEY (`jobId`)     REFERENCES `karigarjobcards` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_karigarledger_user`    FOREIGN KEY (`actorUserId`) REFERENCES `users` (`uid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
