CREATE TABLE `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productGuid` CHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `sku` VARCHAR(40) NOT NULL,
  `huid` CHAR(6) DEFAULT NULL,
  `purityCode` VARCHAR(10) NOT NULL,
  `productDescription` TEXT,
  `grossWeight` DECIMAL(10, 3) NOT NULL,
  `netWeight` DECIMAL(10, 3) NOT NULL,
  `stoneWeight` DECIMAL(10, 3) NOT NULL DEFAULT 0.000,
  `stoneCharges` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  `makingMode` ENUM('flat', 'perGram', 'percent') NOT NULL DEFAULT 'perGram',
  `makingValue` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  `wastagePercent` DECIMAL(5, 2) NOT NULL DEFAULT 0.00,
  `costPrice` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  `tagPrice` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
  `hsnCode` VARCHAR(8) NOT NULL DEFAULT '7113',
  `imagePath` TEXT,
  `isSold` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` DATETIME DEFAULT NULL,
  `mid` INT NOT NULL,
  `sid` INT NOT NULL,
  `pid` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_products_productGuid` (`productGuid`),
  UNIQUE KEY `uk_products_sku` (`sku`),
  UNIQUE KEY `uk_products_huid` (`huid`),
  KEY `idx_mid` (`mid`),
  KEY `idx_sid` (`sid`),
  KEY `idx_pid` (`pid`),
  KEY `idx_products_purityCode` (`purityCode`),
  KEY `idx_products_deletedAt_isSold` (`deletedAt`, `isSold`),
  KEY `idx_products_deletedAt_createdAt` (`deletedAt`, `createdAt`),
  CONSTRAINT `fk_products_mastercategories` FOREIGN KEY (`mid`) REFERENCES `mastercategories` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_products_subcategories`    FOREIGN KEY (`sid`) REFERENCES `subcategories` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_products_productcategories` FOREIGN KEY (`pid`) REFERENCES `productcategories` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_products_purities` FOREIGN KEY (`purityCode`) REFERENCES `purities` (`code`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
