CREATE TABLE `shopsettings` (
  `id` INT NOT NULL,
  `shopName` VARCHAR(150) NOT NULL,
  `gstin` VARCHAR(15) NOT NULL,
  `pan` VARCHAR(10) DEFAULT NULL,
  `addressLine1` VARCHAR(255) NOT NULL,
  `addressLine2` VARCHAR(255) DEFAULT NULL,
  `city` VARCHAR(80) NOT NULL,
  `state` VARCHAR(80) NOT NULL,
  `stateCode` VARCHAR(2) NOT NULL,
  `pincode` VARCHAR(10) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(120) DEFAULT NULL,
  `logoPath` VARCHAR(255) DEFAULT NULL,
  `invoicePrefix` VARCHAR(20) NOT NULL DEFAULT 'INV/',
  `invoiceStartFrom` INT NOT NULL DEFAULT 1,
  `currentInvoiceCounter` INT NOT NULL DEFAULT 1,
  `defaultCurrency` VARCHAR(3) NOT NULL DEFAULT 'INR',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Kolkata',
  `roundOffEnabled` TINYINT(1) NOT NULL DEFAULT 1,
  `backupDir` VARCHAR(255) DEFAULT NULL,
  `defaultPrintVariant` ENUM('a4', 'thermal80') NOT NULL DEFAULT 'a4',
  `repairPrefix` VARCHAR(32) NOT NULL DEFAULT 'REP/',
  `currentRepairCounter` INT NOT NULL DEFAULT 1,
  `whatsappPhoneNumberId` VARCHAR(64) DEFAULT NULL,
  `whatsappBusinessAccountId` VARCHAR(64) DEFAULT NULL,
  `whatsappApiToken` VARCHAR(512) DEFAULT NULL,
  `whatsappEnabled` TINYINT(1) NOT NULL DEFAULT 0,
  `ibjaAutoFetchEnabled` TINYINT(1) NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `chk_shopsettings_singleton` CHECK (`id` = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
